# Generated by Django 5.1.2 on 2024-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shope',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
