# Generated by Django 5.1.2 on 2024-11-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0002_shope_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shope',
            name='contact_details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shope',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
