# Generated by Django 5.1.1 on 2025-04-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0003_shope_contact_details_shope_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sunil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
            ],
        ),
    ]
