# Generated by Django 5.1.2 on 2024-10-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pin',
        ),
        migrations.AddField(
            model_name='customer',
            name='addres',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
