# Generated by Django 5.1.2 on 2024-10-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_remove_customer_pin_customer_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='addres',
            new_name='address',
        ),
    ]
