# Generated by Django 5.1.2 on 2024-10-31 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prise',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Item_weight_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.cart')),
            ],
        ),
    ]
