# Generated by Django 5.1.2 on 2024-10-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_cart_prise_item_weight_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
