# Generated by Django 5.1.2 on 2024-11-01 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_order_master'),
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=1)),
                ('order_filter', models.IntegerField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.customer')),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
                ('stock_item', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.stock_item')),
            ],
        ),
    ]
