# Generated by Django 5.1.2 on 2024-11-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_order_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='weight',
            field=models.IntegerField(default=True),
        ),
    ]
