# Generated by Django 5.1.2 on 2024-11-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_order_detail_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='price',
            new_name='prise',
        ),
    ]
