# Generated by Django 5.1.2 on 2024-11-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_rename_price_order_detail_prise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_weight_detail',
            name='cart',
        ),
        migrations.AddField(
            model_name='item_weight_detail',
            name='cart_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item_weight_detail',
            name='order_detail_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
