# Generated by Django 5.1.2 on 2024-11-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0015_remove_item_weight_detail_order_detail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item',
            name='purchase_amount',
            field=models.FloatField(null=True),
        ),
    ]
