# Generated by Django 5.1.2 on 2024-11-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_stock_item_purchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_category',
            name='shears',
            field=models.FloatField(default=0),
        ),
    ]
