# Generated by Django 5.1.2 on 2024-11-12 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0018_cash_transition'),
        ('sunil', '0003_shope_contact_details_shope_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonepe_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
    ]
