# Generated by Django 5.1.2 on 2024-11-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0019_phonepe_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonepe_number',
            old_name='name',
            new_name='phonepe_name',
        ),
        migrations.RenameField(
            model_name='phonepe_number',
            old_name='mobile',
            new_name='phonepe_number',
        ),
    ]
