# Generated by Django 5.1.2 on 2024-11-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0020_rename_name_phonepe_number_phonepe_name_and_more'),
        ('sunil', '0003_shope_contact_details_shope_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='phonepe_transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('order_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.order_master')),
                ('phonepe_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.phonepe_number')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
    ]
