# Generated by Django 5.1.2 on 2024-11-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0022_order_detail_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
