# Generated by Django 5.1.2 on 2024-11-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0023_cart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
    ]
