# Generated by Django 5.1.2 on 2024-11-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0025_remove_order_detail_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item',
            name='vehicle_charges',
            field=models.FloatField(default=0),
        ),
    ]
