# Generated by Django 5.1.2 on 2024-11-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0026_stock_item_vehicle_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_master',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
