# Generated by Django 5.1.2 on 2025-01-25 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0028_item'),
        ('sunil', '0003_shope_contact_details_shope_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prise', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item')),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
    ]
