# Generated by Django 5.1.2 on 2025-01-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0029_purchase_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_cart',
            name='Item',
        ),
        migrations.AddField(
            model_name='purchase_cart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item'),
        ),
    ]
