# Generated by Django 5.1.2 on 2025-01-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0030_remove_purchase_cart_item_purchase_cart_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_item_weight_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=100, null=True)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
