# Generated by Django 5.1.2 on 2025-01-26 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0032_farmer'),
        ('sunil', '0003_shope_contact_details_shope_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prise', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=1)),
                ('order_filter', models.IntegerField(default=True)),
                ('weight', models.IntegerField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
                ('stock_item', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.stock_item')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_order_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamali', models.FloatField()),
                ('tolai', models.FloatField()),
                ('aadat', models.FloatField()),
                ('shears', models.FloatField()),
                ('eater', models.FloatField()),
                ('total', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('order_filter', models.IntegerField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
    ]
