# Generated by Django 5.1.2 on 2025-01-26 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0034_purchase_order_master_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_item_weight_detail',
            name='Order_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.purchase_order_detail'),
        ),
    ]
