# Generated by Django 5.1.2 on 2025-01-26 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0035_purchase_item_weight_detail_order_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_detail',
            name='stock_item',
        ),
        migrations.AddField(
            model_name='purchase_order_detail',
            name='item',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item'),
        ),
    ]
