# Generated by Django 5.1.2 on 2025-01-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0037_remove_cash_transition_office_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_detail',
            name='stock_status',
            field=models.IntegerField(default=1),
        ),
    ]
