# Generated by Django 5.1.2 on 2025-01-27 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0038_purchase_order_detail_stock_status'),
        ('sunil', '0003_shope_contact_details_shope_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prise', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item')),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
        migrations.CreateModel(
            name='Sell_order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prise', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=1)),
                ('order_filter', models.IntegerField(default=True)),
                ('weight', models.IntegerField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('stock_status', models.IntegerField(default=1)),
                ('item', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item')),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
        migrations.CreateModel(
            name='Sell_item_weight_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=100, null=True)),
                ('weight', models.IntegerField()),
                ('Order_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.sell_order_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Sell_order_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamali', models.FloatField()),
                ('tolai', models.FloatField()),
                ('aadat', models.FloatField()),
                ('shears', models.FloatField()),
                ('eater', models.FloatField()),
                ('total', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('order_filter', models.IntegerField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('farmer', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.farmer')),
                ('office_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.office_employee')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
        migrations.AddField(
            model_name='sell_order_detail',
            name='order_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.sell_order_master'),
        ),
    ]
