# Generated by Django 5.1.2 on 2025-01-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0040_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_order_master',
            name='farmer',
        ),
        migrations.AddField(
            model_name='sell_order_master',
            name='customer',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.customer'),
        ),
    ]
