# Generated by Django 5.1.2 on 2025-02-02 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0044_customer_sell_payment_transaction_and_more'),
        ('sunil', '0003_shope_contact_details_shope_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_purchase_opning_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('type', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.farmer')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
    ]
