# Generated by Django 5.1.2 on 2025-02-09 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0047_remove_customer_purchase_opning_balance_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_purchase_opning_balance',
            name='farmer',
        ),
        migrations.AddField(
            model_name='customer_purchase_opning_balance',
            name='customre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.customer'),
        ),
        migrations.DeleteModel(
            name='Customer_sell_opning_balance',
        ),
    ]
