# Generated by Django 5.1.2 on 2025-02-09 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0048_remove_customer_purchase_opning_balance_farmer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_purchase_opning_balance',
            name='customre',
        ),
        migrations.AddField(
            model_name='customer_purchase_opning_balance',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.customer'),
        ),
    ]
