# Generated by Django 5.1.2 on 2025-02-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0049_remove_customer_purchase_opning_balance_customre_and_more'),
        ('sunil', '0003_shope_contact_details_shope_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_purchase_opning_balance',
            new_name='Customer_sell_opning_balance',
        ),
    ]
