# Generated by Django 5.1.1 on 2025-04-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0050_rename_customer_purchase_opning_balance_customer_sell_opning_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_aadat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_eater',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_hamali',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_shears',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_tolai',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_aadat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_eater',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_hamali',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_shears',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_tolai',
            field=models.FloatField(default=0),
        ),
    ]
