# Generated by Django 5.1.2 on 2025-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0051_item_purchase_aadat_item_purchase_eater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_detail',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sell_order_detail',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
